### ISSUE TITLE
"No warning found" is wrong

### ISSUE THREAD

**Issue by Spielmops** [nucleus-ffm/foss_warn#100]
**Describe the bug**

Fosswarn is running in background (on LineageOS 20 without Gapps). I get a notification from FW. When I open the app, I see a line for my location with "no warning found". I tap on it and get a warning. When I close the warning the location-line has " 1 warning found". 

**Expected behavior**

If we get a notification, then the app should show in the specific location-line "1 (or more) warning found"

Spielmops

**Comment by nucleus-ffm** [comment]
What version of the app are you using? Is this still happening with 0.6.0?

**Comment by Spielmops** [comment]
I have to wait for a warning, will come back, if I know the answer.

Spielmops

**Comment by Spielmops** [comment]
Seems to be OK with version 0.6.0

Spielmops
