### ISSUE TITLE
Wish: I could disable every source of warning

### ISSUE THREAD

**Issue by Spielmops** [nucleus-ffm/foss_warn#108]
I wish, I could disable every source of warning, that is DWD-everything else, Mowas, Biwapp, Katwarn and LHP. That way, I would be able to select the warnings, which aply to my home. I get to many warnings about to much rain or floodings, which are no danger for me.

Spielmops

**Comment by nucleus-ffm** [comment]
We have implemented new notification settings in version 0.7.0. Have the new settings already solved your issue?

**Comment by Spielmops** [comment]
Not yet in Fdroid.
Waiting ...

**Comment by Spielmops** [comment]
Ok, version 0.7.0 ist installed, the settings are now good for me, even better than my wish. Now I'm waiting for warnings ...

Spielmops
