### ISSUE TITLE
version 0.7.0 doesn't find any data

### ISSUE THREAD

**Issue by andyrtr** [nucleus-ffm/foss_warn#114]
After FDroid update to 0.7.0 the app doesn't fimd any data. Neither my stores location nor any warning. I also can't any new location. 
There's only an endlesa spinning circle.

**Comment by nucleus-ffm** [comment]
This should not happen. Is the loading circuit really endless? If the app cannot connect to the Internet, there should be a timeout and an error message after 8 seconds. Do you have any network blocker or something similar installed? Does the error persist when you close and reopen the app? Have you tried deleting the app and reinstalling it?

**Comment by andyrtr** [comment]
I could get the app back working by deleting all app data/cache (again). This shouldn't happen without notice. If it's intentional like on the last update a notice would be nice.
