### ISSUE TITLE
Alert with sound

### ISSUE THREAD

**Issue by Spielmops** [nucleus-ffm/foss_warn#128]
Is alert with sound possible? If yes, please enhance the app with this feature ...

Spielmops

**Comment by nucleus-ffm** [comment]
Can you be a bit more specific? Notifications should have a sound. If you want to customize the sound, you can do that by going to the settings -> open Android-Notification-settings. There, you can select for the different severity levels if you want a sound and, if yes, which sound. The notification sound settings are entirely outsourced to the Android settings.

If you don't mean that, please describe which feature you are missing.

**Comment by Spielmops** [comment]
Now I got it. I didn't know or guess, that were soundsettings behind the different severity-settings.

Thanks,

Spielmops

Am 12. September 2024 23:38:55 MESZ schrieb Nucleus ***@***.***>:
