### ISSUE TITLE
No warning for "Kreis Ludwigsburg"

### ISSUE THREAD

**Issue by ramack** [nucleus-ffm/foss_warn#14]
I added "Kreis Ludwigsburg" in FOSS Warm, but did not get any warning even though there was a NINA warning "Bevölkerungsschutzwarnung vom 11.01.2022, 17:46 Uhr für den Kreis Ludwigsburg:..." today:

https://warnung.bund.de/meldung/mow.DE-BW-S-SE018-20220111-18-000/0/

![p8nRsn0-SRKx6wNgY4PIrg_790f6439e76acd5dc09d2ba78369a8814cf74808](https://user-images.githubusercontent.com/153643/149000501-b561a68e-cb71-4140-b9e1-c4f2b66e0835.jpg)

If I can help anything to debug this, let me know, (BTW thanks a lot for the initiative to create a FOSS Warn APP!)

**Comment by nucleus-ffm** [comment]
Error found and fixed. Ludwigsburg is only in the system as "Ludwigsburg" and not as "Kreis Ludwigsburg". This will be fixed with the next version. It is quite possible that my list contains other errors.
