### ISSUE TITLE
Location list hidden

### ISSUE THREAD

**Issue by Matthias84** [nucleus-ffm/foss_warn#2]
Hi

This is microg LineageOS with default keyboard. As you see the list of locations is not visible. Indeed it is hidden below the virtual keyboard and you need to close it.

![Screenshot_20220104-133730_FOSS_Warn](https://user-images.githubusercontent.com/217511/148063031-41a9f692-3b3c-45d7-837b-7d1389704bd6.png)
![Screenshot_20220104-133737_FOSS_Warn](https://user-images.githubusercontent.com/217511/148063022-636d7646-5f31-4623-a5a0-abae84e3c2b6.png)

Can you tweak the layout, so that it's easier to make use of an autocomplete box or pick from a non textbox list?

**Comment by nucleus-ffm** [comment]
This widget is now moved to a separate screen. This should fix the problem.
