### ISSUE TITLE
Missing Warning for Neustadt a.d. Waldnaab

### ISSUE THREAD

**Issue by Tealk** [nucleus-ffm/foss_warn#21]
As you can see here, there is a warning for Neustadt a.d. Waldnaab that is not displayed.

![Screenshot_20220216-111414.png](https://user-images.githubusercontent.com/12276250/154243761-a6072ec2-d5e8-4580-af75-c74ee5c309b6.png)

![Screenshot_20220216-111436.png](https://user-images.githubusercontent.com/12276250/154243797-f3e3f06e-2622-45c0-be26-36ffee163f87.png)

**Comment by nucleus-ffm** [comment]
Ah, right. That's another problem with the correct spelling. I will fix this in the next version. I hope to fix this kind of problem for all places soon. I've been working on this for a month. I automatically generate a list of places in the API using a Github action [here](https://github.com/nucleus-ffm/nina-api-documentation/blob/main/listOfplaces.txt). In FOSS Warn there are 380 places and in this new list there are 373 places at the moment. So I should have a complete list with the correct spelling soon.

**Comment by Tealk** [comment]
I still have messages that are not displayed

**Comment by nucleus-ffm** [comment]
Have you removed the old location and added it back?  It works fine for me. At the moment there is one warning for Neustadt a.d. Waldnaab. Which message are you missing?

**Comment by Tealk** [comment]
> Have you removed the old location and added it back?

I have not done that yet.

there is no warning at all for me right now. Now I have to wait for a new warning.
