### ISSUE TITLE
AutoStart after ReBoot

### ISSUE THREAD

**Issue by andyrtr** [nucleus-ffm/foss_warn#23]
Using LineageOS 18.1 (Moto X4)/Android 11 the App did not automatically restart after a reboot. Please enable autostart as default behavior and maybe add an option to disable this if wanted. Otherwise one can miss warnings when not checking the app to be running again after a system update or some other reboot/restart.

**Comment by nucleus-ffm** [comment]
That is indeed the case, but it takes some time. But I agree with you that this could be improved.
