### ISSUE TITLE
App resets randomly

### ISSUE THREAD

**Issue by Kurty00** [nucleus-ffm/foss_warn#28]
Using a OnePlus 6 on Oxygen OS 10.3.12 the app resets the settings and locations every few hours.

**Comment by Roxxor91** [comment]
Confirmed on Oneplus 6 running Lineage OS 18.1.

**Comment by nucleus-ffm** [comment]
I am really sorry for the inconvenience. Please do not use the 0.2.7 in F-Droid right now. See [here.](https://github.com/nucleus-ffm/foss_warn/issues/1#issuecomment-1047606997) Please wait for 0.2.8 in F-Droid, use 0.2.7 from Github or use 0.2.6 in F-Droid.

**Comment by Roxxor91** [comment]
> I am really sorry for the inconvenience. 

Don't apologize. No reason to do so. You provide this with your spare time. Thank you for your commitment!

**Comment by nucleus-ffm** [comment]
Version 0.2.8 is now available on F-Droid. It should now work as expected.
