### ISSUE TITLE
Avoid unnessary service notivications 

### ISSUE THREAD

**Issue by Matthias84** [nucleus-ffm/foss_warn#3]
Hi, this is a problem I noticed on LineageOS microg and using KDEconnect.
The App fires a lot of notifications every few minutes, which trigger the kdeconnect an appear on the desktop:
> FOSS Warn ist aktiv

Would it be possible to assign a low priority for this kind of hint notifications but keep the notifications for true emergency warnings high?

**Comment by nucleus-ffm** [comment]
There are two notification channels. One for emergency alert notifications and one for  the status notification. The channel for the status notifications already has a low priority. It is only possible to go one level lower. I will change this in the next release. In the meantime, you can easily disable the status notification in the app settings. Be aware, though, that the background service doesn't always work as expected. Sometimes it gets stopped by the system. So for now, it's better to keep an eye on this.
