### ISSUE TITLE
FOSS Warn cant pull/update in background

### ISSUE THREAD

**Issue by Stefan538871** [nucleus-ffm/foss_warn#30]
My Smartphone always shows that the updating data doesnt work, because the server is not available.
![signal-2022-03-02-010141](https://user-images.githubusercontent.com/1445100/156269457-0028d3e5-1b35-47c6-98cb-63537f6e85ea.png)
Everytime I open the app fetching data seems to work.
Akku optimization is disabled
![signal-2022-03-02-010516](https://user-images.githubusercontent.com/1445100/156269613-d8b25402-71cc-4587-9cbc-906609ba95cb.png)
I use Lineageos 18.1 

If I open the app in the foreground it looks like fetching data does work again as you can see here, since the status changes to "FOSS Warn ist aktive"

any idea if I did something wrong? Or is there a bug?
thx

**Comment by Kelvino9** [comment]
Got the same issue ever since I switched from the Github 0.2.7 to F-Droid 0.2.8

**Comment by nucleus-ffm** [comment]
This seems to be a bug. I am not sure why this is happening now. For now, version 0.2.7 from Gtihub seems to be the best choice until I fix the bug.

**Comment by nucleus-ffm** [comment]
So I found the bug, but I haven't found a working solution yet. Maybe a developer here has a tip for me how to fix it?

The bug occurs only in the background task. The exception is thrown when reading the settings:
> MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

**Comment by nucleus-ffm** [comment]
I think I have fixed the bug now. I will test it now and if everything works I will publish it in the next days.

**Comment by Kelvino9** [comment]
Latest version on F-Droid (0.29) seems to be fixed and functions properly again. Thanks!

**Comment by Stefan538871** [comment]
Just tested it, looks good so far
Thx for the fast fix :)
