### ISSUE TITLE
[UI/UX] Ask for location before showing alerts

### ISSUE THREAD

**Issue by Ryuno-Ki** [nucleus-ffm/foss_warn#35]
Following up [from Mastodon](https://layer8.space/@RyunoKi/107881577601453350) I finally have the time to turn the feedback into an issue.

I was expecting to be asked for a location (either as text input or via GPS) before I can see alerts. This way, I can filter / sort by those, that have the highest priority for me.

**Comment by nucleus-ffm** [comment]
This has been the case for a few versions now. So I think I can close this issue. If it is a problem, feel free to open it again.
