### ISSUE TITLE
Dark theme based on system default

### ISSUE THREAD

**Issue by stefan-niedermann** [nucleus-ffm/foss_warn#36]
It was awesome if one wouldn't need to switch the theme of the app manually to `dark` or `light` but could just choose `system default`, so the app automatically uses either the dark or light theme based on the system preference.

Two personal annotations which are not necessarily relevant for all people:

1. Actually I personally would not even need `dark` or `light` settings, but as an app developer, I know how sustained users are if you woul even try to remove an existing feature 😆 
2. My Android device toggles between `dark` and `light` system theme depending on sunset / sunrise automatically. Adjusting the apps manually is therefore especially "hard work" in my case 😉

**Comment by julianfairfax** [comment]
Yes this would be nice
