### ISSUE TITLE
notifications ui not updating properly

### ISSUE THREAD

**Issue by Stefan538871** [nucleus-ffm/foss_warn#37]
I am not entirely sure if this is just the ui not updating properly or something else
![Screenshot_20220314-132428_Tutanota](https://user-images.githubusercontent.com/1445100/158185561-7cc11de4-d995-4152-a92b-df28395773ab.png)
As you can see in the image the current time is far later then the scheduled time to update.
I use the latest version from fdroid

**Comment by nucleus-ffm** [comment]
This is not a UI issue, but a background task issue. I use a workmanager task and the system always optimizes it, so the frequency with which the task is executed is not constant. This is why you can choose a minimum frequency in the settings and not the actual frequency. When your device goes into sleep mode, the frequency becomes longer and longer. So at the moment it can happen that the task is executed again only after a few hours. This is not optimal and there is already a issue #19 to switch to another mechanism, but this is not ready yet. I had some problems there.

**Comment by Stefan538871** [comment]
Thx for a super fast reply, good to know thx :)
