### ISSUE TITLE
Show previously downloaded warnings even if there is no internet connection

### ISSUE THREAD

**Issue by wsbfimbapb** [nucleus-ffm/foss_warn#40]
Imagine a catastrophic event, where the user has previously downloaded some relevant warning messages, but then

1. the mobile network / internet collapses, or
2. the user has no power source anymore and needs to save as much battery as possible, enabling flight mode to do so.

In both cases, the app shows [this message](https://github.com/nucleus-ffm/foss_warn/blob/main/lib/views/AllWarningsView.dart#L191), yet as a user I would still like to be able read the warning messages. Especially case 1 might occur unexpectedly, such that a user can not preemptively download relevant messages and store them on paper.

**Comment by nucleus-ffm** [comment]
This sounds useful and I will try to implement this in a future release. For now, I would suggest as a "quick fix" to just take a screenshot of the warning.

**Comment by wsbfimbapb** [comment]
Thank you, that sounds great.

**Comment by nucleus-ffm** [comment]
It is now added with version 0.4.1. If you want to test the feature: https://github.com/nucleus-ffm/foss_warn/releases/tag/pre-0.4.1

**Comment by wsbfimbapb** [comment]
Looks good to me. Thanks a lot!
