### ISSUE TITLE
[feature request] option to disable warnings (or notifications) from the DWD

### ISSUE THREAD

**Issue by Quantenzitrone** [nucleus-ffm/foss_warn#43]
I get at least ten notifications of "Amtliche WARNUNG vor STARKEM WETTER" and "Amtliche WARNUNG vor STARKEM GEWITTER", every time when it literally just rains normally.
I am really annoyed by this, so I would like to see a feature to disable warnings by warning source, in my case by the DWD.
Another option (or additional) could be to have notifications split between every warning source, so I can decide what notifications I get and how loud they will be.
I also don't just want to uninstall FOSS Warn, because I think having this app can be really crucial for some important warnings and I like that I get updates of COVID-19 rules.

**Comment by nucleus-ffm** [comment]
There is now a test-version with more control over what events you want to be notified for. Feel free to test it and let me know if it works as expected. https://github.com/nucleus-ffm/foss_warn/releases/tag/0.3.0

**Comment by Quantenzitrone** [comment]
looks good

ill have to wait for the next rain to test it tho
