### ISSUE TITLE
Abgleich deutscher Ortschaften und Kreise via API des Bundes?

### ISSUE THREAD

**Issue by Lukas2112** [nucleus-ffm/foss_warn#47]
Stellt der Bund (über das Bundesministerium des Innern und für Heimat; BMI oder einer vergleichbaren Behörde im Geschäftsbereich des BMI) eine Liste von Ortschaften und Kreisen innerhalb des Bundesgebiet der Bundesrepublik bereit, welche sich maschinell abgleichen ließe? Glaube zwar nicht, aber vielleicht ja doch?

**Comment by nucleus-ffm** [comment]
Ich habe bisher noch keine gefunden. Auf [bund.dev](https://bund.dev/) steht dazu auch nichts. Für FOSS Warn hatte ich deshalb meine eigene [Liste](https://github.com/nucleus-ffm/nina-api-documentation/blob/main/listOfplaces.txt) erstellt. Für diese 380 Orte gibt es über NINA und co. Warnungen.

**Comment by nucleus-ffm** [comment]
Ich habe die Tage noch das [hier]( https://www.xrepository.de/api/xrepository/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:rs_2021-07-31/download/Regionalschl_ssel_2021-07-31.json) gefunden. Da stehen aber auch Ortschaften drin, für die es keine Warnmeldungen gibt. Aber je nach dem für was, ist das vielleicht das Richtige.
