### ISSUE TITLE
[UI/UX] Change the display of the date format

### ISSUE THREAD

**Issue by Lukas2112** [nucleus-ffm/foss_warn#5]
My idea would have been to change the text "Message on: dd.mm.yyyy at hh:mm hrs" to "Message on dd.mm.yyyy (or dd. month (written out) yyyy) at hh:mm hrs".

**Comment by nucleus-ffm** [comment]
I am not sure if I have understood this correctly. You suggest removing the ":" and perhaps writing out the month? Why would that be better than now?

**Comment by Lukas2112** [comment]
Maybe it's just a personal preference, but my thought was that without a colon it somehow seems more fluid - unfortunately I don't know how else to describe it.
