### ISSUE TITLE
More translations

### ISSUE THREAD

**Issue by julianfairfax** [nucleus-ffm/foss_warn#53]
Please add the following to https://github.com/nucleus-ffm/foss_warn/wiki/Translation-for-Swiss (perhaps make the wiki editable?):
- Alle Meldungen = All alerts
- Einstellungen = Settings
---
- Wie sollen die Meldungen sortiert werden = How to sort the messages
- (neuste zuerst) = (newest first)
- (höchste zuerst) = (highest first)
- schließen = close
---
- Alle warnungen als gelesen markiert = All warnings marked as read
---
- Waldbrand = Forest fire
---
- Betroffene region = Affected region
- Betroffene Orte = Affecteed place
- Beschreibung = Description
- Quelle der Meldung = Source of the alert
- Kontakt und Website = Contact and website
---
- Es gibt [Nummer] Warnung = There is/are [number] warning/warnings
- Keine Warnungen gefunden = No warnings found
---
- Ortsname oder Kreisname = Place name or country name
- Die folgende Liste könnte Fehlerhaft sein, wordurch es zu keiner Warnung kommt. Wenn Fehler auffalen, bitt Bescheid geben. = The following list may contain errors, which will not result in a warning. If you find any errors, please let us know.
---
- Ort löschen? = Delete location?
- Bist Du sicher, dass Du diesen Ort löschen möchtest? = Are you sure you want to delete this place?
- Abbrechen = Cancel
- Löschen = Delete
---
- Öffnet die Einstellungen für was eine Benachrichttung gesendet werden soll = Opens the settings for what a notification should be sent
- Status-Benachrichttung anzeigen = Show status notification
- Zeigt eine Benachrichttung mit der Uhrzeit der letzen Aktualisierung = Displays a notification with the time of the last update
- Hintergrundbenachrichtungen für hinterlegte Orte = Background notifications for stored locations
- Wenn eingeschaltet prüft FOSS Warn im Hintergrung ob es Warnungen für hinterlegte Orte gibt = If enabled, FOSS Warn checks in the background if there are warnings for stored locations
- Darstellung = Presentation
- Startansicht beim Öffnen = Home view when opening
- Zeige erweiterte Metadaten bei Meldungen = Show extended metadata for alerts
- Zeige alle Meldungen an = Show all alerts
- Wenn aktiviert werden in der Ansicht 'Alle Meldungen' nicht nur die Meldungen für Dine Orte angezeigt, sonden alle verfügbaren Meldungen aus ganz Deustschland = If activated, the 'All alerts' view shows not only the alerts for your locations, but also all available messages from all over Germany.
- Wähle eine Schriftgröße = Choose a font size
- klein = small
- Normal = Normal
- Groß = Large
- Extragroß = Extra large
---
My apologies if I included something that is already included, or missed something. I did not do the dev settings, the alert sources area, or the initial setup button or screen.

We should really have a translation service like [Weblate](https://github.com/WeblateOrg) so we can contribute these translations into the app itself.

In the meantime, you should also probably change Swiss to just say Translation to English or something, since English isn't an official language of Switzerland anyway.

Thanks again for making this, and I'm looking forward to seeing it progress more (what with translations, system dark mode, adaptive icon, material you?, otherwise better accent colour, hint hint #50)!

**Comment by nucleus-ffm** [comment]
Thank you. I have added it to the list and changed the title to https://github.com/nucleus-ffm/foss_warn/wiki/Translation-of-the-UI-into-English
