### ISSUE TITLE
Clicked on a notification but the announcements list was empty

### ISSUE THREAD

**Issue by MatsG23** [nucleus-ffm/foss_warn#55]
A few days ago, I clicked on notification of the app that just appeared. The app opened and showed an empty lists of announcements. 
I could workaround this issue by reloading the list.

**Comment by nucleus-ffm** [comment]
i tried to fix this with https://github.com/nucleus-ffm/foss_warn/commit/8ba59d26005b27145cf82df4a8f5082aa12e4a37  We are now reloading and displaying the loading screen when the application resumes. We should check if the problem is fixed now.
