### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [nucleus-ffm/foss_warn#79]
ref: [de.nucleus.foss_warn_26.log.gz](https://github.com/nucleus-ffm/foss_warn/files/10519886/de.nucleus.foss_warn_26.log.gz)

Also tried Flutter 3.7.0 but fails differently

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/29ee5eefb25249f041448240023dcfc733cbe562

**Comment by nucleus-ffm** [comment]
Now that FOSS Warn is localized, the build script needs to be modified. The reason why the build fails is that the app_localizations.dart is missing. This code is generated when `flutter gen-l10n` [0] is executed. I think this should fix the error.

[0] https://docs.flutter.dev/development/accessibility-and-localization/internationalization

**Comment by licaon-kter** [comment]
Trying now...

**Comment by licaon-kter** [comment]
Fixed, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/efbaeeabd30a4f40f285487065ac098cfb2e415e
