### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [nucleus-ffm/foss_warn#85]
https://hosted.weblate.org/projects/foss-warn/#information says AGPLv3-only,
whereas https://github.com/nucleus-ffm/foss_warn/blob/main/LICENSE (not specified "only" or "or later"), so they aren't compatible.

https://github.com/nucleus-ffm/foss_warn/blob/ad09d8d29e197ccf7580c884fce51e1343c0314c/lib/views/aboutView.dart#L176
says GPLv3 (not specified "only" or "or later").

It would be better to make the translations GPLv3-or-later in
https://hosted.weblate.org/settings/foss-warn/foss-warn-app/
https://hosted.weblate.org/settings/foss-warn/glossary/

And additionally specify "or later" or the code somewhere.
Maybe I missed an intention to make it "GPLv3-only", but usually it is the case that people just select the wrong thing.

**Comment by nucleus-ffm** [comment]
@comradekingu That was actually indented, but maybe we should reconsider that decision. My initial thought was that I don't want to support a license that doesn't exist yet, because I can't know what's in the new license. And if there is a newer version of the GPL, I want to change it manually. But maybe there is no need to worry.

**Comment by comradekingu** [comment]
That is exactly what you have to do, it is not automatic.
My worry is that you will be in a situation where you want to change, and then have to negotiate licensing with each and every translator.

**Comment by nucleus-ffm** [comment]
@comradekingu OK, your right. I have now selected GPLv3 or later in Weblate. So that should be fine now, right?

**Comment by comradekingu** [comment]
@nucleus-ffm
Except it isn't pushing anything here. If you add "kingu" in https://hosted.weblate.org/access/foss-warn/#users I can have  a look.

**Comment by nucleus-ffm** [comment]
@comradekingu Oh yes, I had to change the push URL. Now it seems to work: https://github.com/nucleus-ffm/foss_warn/commit/1016a8fc1b21592f33a1962cada4d394b4b29e45
